// The Community Hub's dialogs: its rules (shown before every upload, and
// from the account menu), and the picker that chooses which of your Fakémon
// to publish or to replace a listing with.

import { useMemo, useState } from 'react';
import { api, state } from '../../core/app.ts';
import { Icon } from '../components/Icon.tsx';
import { Modal } from '../components/Modal.tsx';
import { registerDialog, type DialogProps } from '../dialogs.tsx';
import type { Fakemon } from '../types.ts';

// ==================== rules ====================

type RulesProps = DialogProps<{ requireAgreement?: boolean; onAccept?: (() => void) | null }>;

function CommunityRulesDialog({ close, requireAgreement = false, onAccept = null }: RulesProps) {
    const [agreed, setAgreed] = useState(false);
    function accept() {
        if (!agreed) { api.showToast?.('Please agree to the Community Rules first.', 'warning'); return; }
        api.markCommunityRulesAccepted?.();
        close();
        onAccept?.();
    }
    return (
        <Modal onClose={close} className="policy-modal community-rules-modal" labelledBy="community-rules-title"
            title={requireAgreement ? 'Community Rules Before Publishing' : 'Community Rules'}>
            <div className="modal-body policy-body">
                <p>Keep the Community Hub friendly, creative, and safe for everyone.</p>
                <ul>
                    <li><strong>We strictly do not allow AI art.</strong> Artwork must be drawn by a human being. Anything generated by an AI image tool, or traced, painted over, or touched up from a generated image, will be removed. Repeat uploads are grounds for a permanent ban. If you did not draw it, credit the artist who did.</li>
                    <li><strong>No NSFW or sexual content.</strong> This includes artwork, names, descriptions, cries, and other uploaded content.</li>
                    <li><strong>No inappropriate or offensive names.</strong></li>
                    <li><strong>No spam.</strong> Do not flood the Community Hub with repeated or low-effort posts.</li>
                    <li><strong>No harassment, threats, hate, or discrimination.</strong></li>
                    <li><strong>No impersonation.</strong> Do not pretend to be another user, creator, staff member, company, or organization.</li>
                    <li><strong>No scams, misleading content, or advertising.</strong></li>
                    <li><strong>Only share content you have permission to use.</strong></li>
                    <li><strong>Do not upload malicious or harmful files.</strong></li>
                </ul>
                <p>Breaking these rules may result in content removal, account termination, and a permanent ban from the Community Hub and Woogidex.</p>
                <div className="policy-actions">
                    <div className="policy-check-row" style={{ display: 'flex' }}>
                        <label className="auth-terms-check">
                            <input type="checkbox" checked={agreed} onChange={e => setAgreed(e.target.checked)} />
                            <span>I have read and agree to the Community Rules.</span>
                        </label>
                    </div>
                    <button type="button" className="btn btn-primary" onClick={accept}>I Agree and Continue</button>
                </div>
            </div>
        </Modal>
    );
}

// ==================== pick one of your Fakémon ====================

type SortKey = 'created' | 'name' | 'number' | 'bst' | 'updated';
type PickerProps = DialogProps<{ mode: 'publish' | 'update'; targetId?: string | null; preselectId?: string }>;

const bst = (f: Fakemon): number => Number(api.getFakemonBST?.(f)) || 0;
const dex = (f: Fakemon) => { const n = parseInt(String(f.number || '').replace(/^#/, ''), 10); return Number.isFinite(n) ? n : Number.POSITIVE_INFINITY; };

function CommunityPickerDialog({ close, mode, targetId = null, preselectId = '' }: PickerProps) {
    const collection: Fakemon[] = (state.fakemonDB || []).filter(f => !f.pendingVanilla);
    const [search, setSearch] = useState('');
    const [sortBy, setSortBy] = useState<SortKey>('created');
    const [order, setOrder] = useState<'asc' | 'desc'>('desc');
    const [selected, setSelected] = useState(() => (collection.some(f => String(f.id) === String(preselectId)) ? String(preselectId) : ''));
    const publishing = mode === 'publish';

    const shown = useMemo(() => {
        const q = search.trim().toLowerCase();
        const dir = order === 'asc' ? 1 : -1;
        return collection
            .filter(f => !q || String(f.name || '').toLowerCase().includes(q) || String(f.number || '').toLowerCase().includes(q))
            .sort((a, b) => {
                if (sortBy === 'name') return String(a.name || '').localeCompare(String(b.name || '')) * dir;
                if (sortBy === 'number') return (dex(a) - dex(b)) * dir;
                if (sortBy === 'bst') return (bst(a) - bst(b)) * dir;
                if (sortBy === 'updated') return ((Number(a.updatedAt) || 0) - (Number(b.updatedAt) || 0)) * dir;
                return ((Number(a.createdAt) || 0) - (Number(b.createdAt) || 0)) * dir;
            });
    }, [collection, search, sortBy, order]);
    const current = collection.find(f => String(f.id) === selected);

    function confirm() {
        if (!selected) { api.showToast?.('Choose a Fakémon from your collection first.', 'warning'); return; }
        close();
        if (publishing) { api.publishFakemon(selected); return; }
        if (!targetId) { api.showToast?.('That listing could not be found.', 'error'); return; }
        api.updatePublishedMon(targetId, selected);
    }

    return (
        <Modal onClose={close} className="community-update-modal" title={publishing ? 'Choose a Fakémon to publish' : 'Choose a Fakémon to update'}>
            <div className="modal-body community-update-modal-body">
                <p className="community-update-help">
                    {publishing
                        ? 'Pick the Fakémon from your collection to publish to the community hub. Its evolution stages, megas and formes go up with it as one post.'
                        : 'Select the Fakémon from your collection that should replace this community hub upload.'}
                </p>
                <div className="community-update-controls">
                    <div className="community-update-search-wrap">
                        <Icon name="search" />
                        <input type="search" placeholder="Search your Fakemon..." value={search} onChange={e => setSearch(e.target.value)} autoFocus />
                    </div>
                    <select value={sortBy} onChange={e => setSortBy(e.target.value as SortKey)} aria-label="Sort collection">
                        <option value="created">Date Added</option><option value="name">Name</option><option value="number">Pokédex Number</option><option value="bst">BST</option><option value="updated">Last Updated</option>
                    </select>
                    <select value={order} onChange={e => setOrder(e.target.value as 'asc' | 'desc')} aria-label="Sort direction">
                        <option value="desc">Descending</option><option value="asc">Ascending</option>
                    </select>
                </div>
                <div className="community-update-collection-grid">
                    {shown.length ? shown.map(f => {
                        const id = String(f.id);
                        const number = f.number ? `#${String(f.number).replace(/^#/, '')}` : '';
                        const total = bst(f);
                        return (
                            <button key={id} type="button" className={`community-update-mon-card${id === selected ? ' selected' : ''}`} onClick={() => setSelected(id)}>
                                <div className="community-update-mon-art">
                                    {f.artwork
                                        ? <img src={f.artwork} alt={f.name || 'Fakemon'} loading="lazy" decoding="async" />
                                        : <img className="no-art-placeholder" src="assets/no_art_placeholder.png" alt="No artwork" />}
                                </div>
                                <div className="community-update-mon-info">
                                    <strong>{f.name || 'Unnamed Fakemon'}</strong>
                                    <span>{number}{number && total ? ' · ' : ''}{total ? `BST ${total}` : ''}</span>
                                </div>
                            </button>
                        );
                    }) : <div className="community-update-empty">No Fakemon match your search.</div>}
                </div>
                <div className="community-update-actions">
                    <div className="community-update-selected">{current ? `Selected: ${current.name || 'Unnamed Fakemon'}` : 'No Fakemon selected'}</div>
                    <div className="community-update-action-buttons">
                        <button className="btn btn-secondary" type="button" onClick={close}>Cancel</button>
                        <button className="btn btn-primary" type="button" disabled={!current} onClick={confirm}>
                            {publishing ? <><Icon name="upload" size={14} /> Publish</> : <><Icon name="refresh-cw" size={14} /> Update listing</>}
                        </button>
                    </div>
                </div>
            </div>
        </Modal>
    );
}

registerDialog('community-rules', CommunityRulesDialog);
registerDialog('community-picker', CommunityPickerDialog);
